skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
calculator_contract_using_anchor = "oeF25mZ1BWEWQsnLY3xJcQK2YiJW8ZYeDgv8DCz1i9E"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
