skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_learning = "GExRzsc5SXeT9ocYoTv3wJ36x77onZyAZUq67MVqQ8cj"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
